name: DevOps Lab ARM Demo - CICD

on: 
  push:
    branches:
      - master

env: 
  subscriptionid: b69c2a11-bd8a-4349-b9d9-1c55bd839199

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    # checkout code from repo
    - name: Checkout code
      uses: actions/checkout@v1
      
    # setup nuget
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1

    # copy zip to staging
    - name: Build solution
      run: |
        mkdir staging
        copy .\Deploy\Tailwind.Traders.web.zip .\staging
        copy .\Deploy\AzCLI\deployWebApp.ps1 .\staging

    # upload build artifact
    - name: Publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: staging

  provisionAndConfigure:
      name: Deploy to staging
      runs-on: ubuntu-latest
      env: 
        resource_group_name: DevOpsLabARMDemoRG
        location: west us 2
      environment: 
        name: staging
      steps:
        # checkout code from repo
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Azure login
          uses: Azure/login@v1
          with:
              creds: ${{ secrets.SERVICE_PRINCIPAL_SECRET}}
        # provision and configure infrastructure using azure cli deploying arm template
        - name: Deploy ARM template 
          uses: Azure/arm-deploy@v1
          with:
            scope: subscription
            subscriptionid: ${{env.subscriptionid}}
            region: "${{env.location}}"
            template: ./Deploy/ARM/tt-iac.json

 
  # deploy:
  #   needs: [build, provisionAndConfigure] 
  #   runs-on: windows-latest
  #   steps:
      
  #     # download build artifacts
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@master
  #       with:
  #         name: webapp

  #     - name: show webapp directory
  #       run: |
  #         echo ls
  #         ls
          
  #     # deploy web app
  #     - name: Deploy web app
  #       env:
  #         SERVICE_PRINCIPAL: 44d50836-35fe-4029-87d5-697bcefc60c6
  #         SERVICE_PRINCIPAL_TENANT: 4b33b6e8-313b-489d-a02b-725af517deab
  #         RESOURCE_GROUP: DevOpsLabARMDemoRG
  #         WEB_APP_NAME: devopslabtt
  #         PATH_TO_WEBSITE_ZIP: .\Tailwind.Traders.web.zip
  #       run: >
  #         powershell -command "& ./deployWebApp.ps1 "
  #         -servicePrincipal %SERVICE_PRINCIPAL% 
  #         -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
  #         -servicePrincipalTenantId %SERVICE_PRINCIPAL_TENANT% 
  #         -resourceGroupName %RESOURCE_GROUP% 
  #         -webAppName %WEB_APP_NAME% 
  #         -pathToWebsiteZip %PATH_TO_WEBSITE_ZIP% 
